### ISSUE TITLE
Support node scans when variables have the same label and property

### ISSUE THREAD

**Issue by pstutz** [opencypher/morpheus#171]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/api/spark/CAPSPatternGraphTest.scala#L389

**Comment by boggle** [comment]
Not sure I understand this, could you please add some details?

**Comment by pstutz** [comment]
It's linked to a test where an employee and a person both have a property `name`, and in one case it's nullable. That test is ignored, because it currently fails for something that is both an employee and a person.
