### ISSUE TITLE
Avoid passing manually constructed maps into RecordHeader

### ISSUE THREAD

**Issue by s1ck** [opencypher/morpheus#519]
happens in
* StructType -> RecordHeader conversion
* EntityMapping -> RecordHeader conversion

**Comment by Mats-SX** [comment]
@s1ck Why do we want to avoid 'manually constructed maps'? What would we do instead?

Looking at 

https://github.com/opencypher/cypher-for-apache-spark/blob/8d70bedd07bce09f6464001dc69639d4cae74fa4/spark-cypher/src/main/scala/org/opencypher/spark/impl/convert/SparkConversions.scala#L109-L122

Here we do 'manually' construct a map, but is it a smell?

**Comment by s1ck** [comment]
I guess we added that issue to make sure that the header is only modified through the exposed `with[...]` methods and we don't expose internals. In the example you shared this would be possible:
```
structType.fields.foldLeft(RecordHeader.empty) {
  case (currentHeader, field) => 
    // type validation...
    val expr = Var(field.name)(cypherType)
    header.withExpr(expr).withColumnRenamed(expr, field.name)
```
This would use only header modification methods and hides internals. Not sure if that's high prio atm, but I can open a PR if you think it makes sense.

**Comment by Mats-SX** [comment]
I understand. That makes sense, but isn't urgent. Can be fixed when convenient.
