### ISSUE TITLE
Update to newer Hadoop version

### ISSUE THREAD

**Issue by pstutz** [opencypher/morpheus#626]

**Comment by Mats-SX** [comment]
Aren't we tied to what Spark uses here?

**Comment by pstutz** [comment]
In general the Spark 2.2 documentations says: ["Downloads are pre-packaged for a handful of popular Hadoop versions. Users can also download a “Hadoop free” binary and run Spark with any Hadoop version by augmenting Spark’s classpath."](https://spark.apache.org/docs/2.2.0/)

I added the issue when I ran into problems the HadoopMinicluster we use in our tests, as we use a very old Hadoop version and that caused all kinds of problems. So ideally we are agnostic as well, and maybe we can/should get rid of HadoopMinicluster in our tests. It's been a while that I ran into these problems, I think they were related to testing the S3 data source.
