### ISSUE TITLE
Verify correct id generation for parallel edges with same label

### ISSUE THREAD

**Issue by s1ck** [opencypher/morpheus#809]
The current id generation strategies `HashBasedId` and `SerializedId` use all columns + some meta info of an egde DF to compute the new id. This might lead to id collisions in the case of parallel edges. We should add a PGDS acceptance and verify. 

One solution would be to add a random number into the selected columns. Another solution would be to add the monotonically increasing id to the DF and merge it into the previously generated id.

**Comment by FlorentinD** [comment]
#929
