### ISSUE TITLE
Remove Graph from CTNode / CTRelationship equality

### ISSUE THREAD

**Issue by DarthMax** [opencypher/morpheus#819]
Currently the optional graph name is part of CTNode / CTRelationship equality. 
Sometimes these are not known but we would still like to check for equality.

Is there any thing that would speak against moving the graph into a seconds argument list?

**Comment by Mats-SX** [comment]
How can we check for equality if we can't know if the nodes are from the same graph? Only nodes in the same graph are equal, aren't they?
