### ISSUE TITLE
Support list comprehensions

### ISSUE THREAD

**Issue by iansrobinson** [opencypher/morpheus#834]
After a COLLECT, list access via a single index is supported, but list comprehensions are not:

`
org.opencypher.okapi.impl.exception.NotImplementedException: The expression ListComprehension(ExtractScope(Variable(x),None,Some(ContainerIndex(Variable(  pymks@271),Variable(x)))),FunctionInvocation(Namespace(List()),FunctionName(range),false,Vector(Parameter(  AUTOINT2,Integer), Parameter(  AUTOINT3,Integer)))) [line 8, column 24 (offset: 300)] is not supported by the system
`

**Comment by jjaderberg** [comment]
That is correct, list comprehension is not supported yet. You can see the currently supported Cypher 9 features at https://github.com/opencypher/cypher-for-apache-spark/blob/master/documentation/asciidoc/cypher-cypher9-features.adoc

**Comment by FlorentinD** [comment]
#914 :tada:
