### ISSUE TITLE
Hitting a performance issue during query execution trying to create dataframe for every node/edge.

### ISSUE THREAD

**Issue by nagrawal79** [opencypher/morpheus#879]
I am hitting a performance issue. Where spark driver during loading graph at

session.catalog().graph(<graphname>) is taking a lot of time. 

From thread dump of spark executor I can see that time is doing in trying to create a DataFrame for every vertex and edge sequentially. 

Is there a way or workaround to skip creating DataFrame? Is there a way to create DataFrame for different vertex/edges in parallel.

**Comment by pstutz** [comment]
Hi @nagrawal79, thank you for reporting the issue you encountered. The system should not generate a separate DataFrame for each node/relationship. How do you create the graph? Could you please post an example that allows us to reproduce the issue?

**Comment by nagrawal79** [comment]
I create it using 
CAPSSession session = CAPSSession.create(sparkSession);
this.registerGraphSource(session, hdfsPath, config);
PropertyGraph purchaseGraph = session.catalog().graph("olapGraph." + graphName);

graph function internally create a list of CAPSNodeTable and CAPSRelationshipTable one of each vertex and edge respectively. This happens sequentially in spark driver.

 Whenever a CAPSNodeTable or CAPSRelationshipTable is create a DataFrame object is passed to constructor. This DataFrame is corresponding to node and relationship directory.

**Comment by Mats-SX** [comment]
@nagrawal79 Could you please provide a code snippet from your program? It is difficult to analyse what is going wrong at this point.

**Comment by s1ck** [comment]
Closing this. @nagrawal79 feel free to re-open with more details if it's still an issue
