### ISSUE TITLE
how to connect to  Hive using the thrift protocol 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [opencypher/morpheus#890]
I wonder how to connect to hive installed on my machine and create HiveDB/Tables  using the thrift protocol, rather than creating them locally (metastore) in the project

**Comment by Mats-SX** [comment]
@MohamedRagabAnas I believe you should be able to do this as per usual with your `SparkSession`, and then wrap this in a `CAPSSession` using the `CAPSSession.create()` call.

I have no particular expertise on Hive or Thrift, but the general model we take is that we try to just extend the capabilities that you get with Apache Spark itself, so if this is something you know how to do with standard Spark my best advice is to try that with CAPS as well.

**Comment by MohamedRagabAnas** [comment]
Yes, Done Thank You very much @Mats-SX

**Comment by MohamedRagabAnas** [comment]
Please, @Mats-SX  could you tell me how to generate the graph from the created already tables and views in hive, rather than dropping the database and recreating the DDL again ?!
Thanks in advance for your support and help

**Comment by Mats-SX** [comment]
@MohamedRagabAnas There are essentially two ways of achieving this. The most sophisticated is to use the `SQLPropertyGraphDataSource`. You can read our manual on how to use and configure it here: https://neo4j.com/docs/morpheus-user-guide/preview/caps/backends/sql/

You'll be using Graph DDL, which is a language we've invented to map a graph from a SQL system (table-based database (abstraction)). To not repeat everything from the manual, what you'll need to do is roughly:

1. Define element types (abstract nodes and relationships)
2. Define node and relationship types
3. Define a graph type (consisting of the above)
4. Map a graph instance from SQL tables (in your case Hive)

I also recommend reading the [CensusHiveExample](https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/CensusHiveExample.scala) which seems to match your use case fairly well (as far as I've understood).

**Comment by Mats-SX** [comment]
@MohamedRagabAnas I'm closing this as settled. If you still have issues with this, please just comment and we can reopen the issue.
