### ISSUE TITLE
Hive avoiding database and table already exists exceptions on re-runs

### ISSUE THREAD

**Issue by MohamedRagabAnas** [opencypher/morpheus#898]
How to deal with the production (not-in-memory) hive store with CAPS, and avoid database and table already exists exceptions on re-runs.

Thanks in advance for your prompt help!

**Comment by Mats-SX** [comment]
@MohamedRagabAnas Could you provide a bit more detail on what exactly it is you're trying to do? Do you have code snippets to share? CAPS does not add any functionality on creating Hive (or other) databases, so I'm not sure exactly what you are referring to.
