### ISSUE TITLE
datetime function

### ISSUE THREAD

**Issue by MohamedRagabAnas** [opencypher/morpheus#904]
Is datetime() function is supported in CAPS because while invoking it it gives me an error !!
what I want to make is to compare two datetimes if they are already stored as strings in this format ''2015-06-24T12:50:35.556+0100''

**Comment by DarthMax** [comment]
Hej there, 

unfortunately Spark does not support any for of localized temporal values. This is why CAPS currently only supports `localdatetime`.

You can use it as described here: 
https://neo4j.com/docs/cypher-manual/current/functions/temporal/localdatetime/

In general CAPS allows comparing temporal values. However localdatetime does not support parsing date strings with a time zone, so you would have to remove that part (e.g. using substring).
