### ISSUE TITLE
Converting Milliseconds GMT Date to years and Months Issue

### ISSUE THREAD

**Issue by MohamedRagabAnas** [opencypher/morpheus#936]
Hi, There 
I'm wondering what is the best way to take the year and month from the Milliseconds GMT Date ( 1313591219961) in Morpheus Cypher. 
I'm using basic calculations to get the year and month from this date, it works fine in neo4j, but this gives me some error with Morpheus Cypher!
   
      |MATCH
      |  (home:Country{name:'Germany'})<-[:IS_PART_OF]-(:City)<-[:IS_LOCATED_IN]-
      |  (:Person)<-[:HAS_CREATOR]-(message:Message)-[:IS_LOCATED_IN]->(destination:Country)
      |WHERE home <> destination
      |WITH
      |  message,
      |  destination,
      |  ( (message.creationDate%31556952000) /2592000000 +1 ) AS month
      |RETURN
      |  count(message) AS messageCount,
      |  destination.name,
      |  month
      |ORDER BY
      |  messageCount DESC,
      |  destination.name ASC,
      |  month ASC
      |LIMIT 100
    
Error shown is: 

`Exception in thread "main" org.opencypher.okapi.impl.exception.NotImplementedException: Not yet able to convert expression: Modulo(Property(Variable(message),PropertyKeyName(creationDate)),Parameter(  AUTOINT1,Integer))`

Thanks in advance for your help!

**Comment by Mats-SX** [comment]
The reason you get this error is because the modulo operator (`%`) is not yet implemented. If you try to do your calculations without it, perhaps you can work around this limitation?

It would probably be easy to add this function, however we are not actively looking at additional features for Morpheus currently.

**Comment by Mats-SX** [comment]
The modulo operator expression (`%`) has now been implemented.
