### ISSUE TITLE
Morpheus Running Cypher Query Issue

### ISSUE THREAD

**Issue by MohamedRagabAnas** [opencypher/morpheus#937]
Hi there, 
I'm trying to run this query (from teh LDBC SNB BI query workloads) in Morpheus, but it gives me the following error. 

      """
        |
        |MATCH (message:Message)
        |WHERE message.creationDate < 1313591219961
        |WITH count(message) AS totalMessageCountInt
        |WITH toFloat(totalMessageCountInt) AS totalMessageCount
        |MATCH (message:Message)
        |WHERE message.creationDate < 1313591219961
        |  AND message.content IS NOT NULL
        |WITH
        |  totalMessageCount,
        |  message,
        |  (message.creationDate/31556952000+1970) AS year
        |WITH
        |  totalMessageCount,
        |  year,
        |  message:Comment AS isComment,
        |  CASE
        |    WHEN message.length <  40 THEN 0
        |    WHEN message.length <  80 THEN 1
        |    WHEN message.length < 160 THEN 2
        |    ELSE                           3
        |  END AS lengthCategory,
        |  count(message) AS messageCount,
        |  floor(avg(message.length)) AS averageMessageLength,
        |  sum(message.length) AS sumMessageLength
        |RETURN
        |  year,
        |  isComment,
        |  lengthCategory,
        |  messageCount,
        |  averageMessageLength,
        |  sumMessageLength,
        |  messageCount / totalMessageCount AS percentageOfMessages
        |ORDER BY
        |  year DESC,
        |  isComment ASC,
        |lengthCategory ASC
      """

```
ERROR [task-result-getter-1] scheduler.TaskSetManager (Logging.scala:logError(70)) - Task 11 in stage 6.0 failed 4 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 11 in stage 6.0 failed 4 times, most recent failure: Lost task 11.3 in stage 6.0 (TID 81, 172.17.64.231, executor 2): java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.spark.rdd.MapPartitionsRDD.f of type scala.Function3 in instance of org.apache.spark.rdd.MapPartitionsRDD
```

**Comment by MohamedRagabAnas** [comment]
@Mats-SX  @pstutz  could you help in this, Thanks in advance

**Comment by Mats-SX** [comment]
Hello @MohamedRagabAnas and apologies for not responding. Unfortunately, we can not promise that we will have a look at this, given that Morpheus is not in active development. I would like to refer to #950 for a more comprehensive answer.

I will close this as a wont-fix for now.
