### ISSUE TITLE
Access nested properties of data frame when map to a PG element

### ISSUE THREAD

**Issue by goshaQ** [opencypher/morpheus#940]
When a node table is created from a data frame with specified nested properties (like "foo.bar") the [ElementTable verification](https://github.com/opencypher/morpheus/blob/9f500f5364c0ba14933d96d088d5a8501d4644ad/okapi-relational/src/main/scala/org/opencypher/okapi/relational/api/io/ElementTable.scala#L113) fails. I guess the problem is because of direct comparison of whether column names of a data frame match with the provided one. Instead first should be ensured that provided property names contain nested properties (and those "foo.bar" actually present in the data frame).

I also don't get it why the verification happens at ElementTable creation, if this is already done by Spark during column name resolution?

**Comment by s1ck** [comment]
Okapi does not support nested columns in the input element tables. Each column specified in the `ElementMapping` must be present in the table (i.e. `DataFrame`). Your solution for that would be flattening those nested columns before using the `DataFrame` as input `ElementTable`.

To your second question. Note, that Okapi is abstract and doesn't have any specific dependency to Spark. That being said, we need to ensure valid input as we cannot guarantee the backend to do the proper validation.

**Comment by goshaQ** [comment]
@s1ck Thanks for your answer! The point with okapi that is abstract makes things clear.

But I wonder if there is limitations in current design to add support of nested columns in the input `DataFrameTable`? Just to me it looks strange to first flatten the input and then define the same mapping again.

But I guess this feature is more like nice to have, so feel free to close the issue.

**Comment by s1ck** [comment]
We were also playing with the idea of supporting nested columns already in Okapi. It's good that you voiced that requirement. Stay tuned :)
