### ISSUE TITLE
State of morpheus?

### ISSUE THREAD

**Issue by MarcianoAvihay** [opencypher/morpheus#943]
it's been a while since there was an update regarding the current state of events - especially with the (upcoming?) release of spark 3.0 - i want to cautiously try using morpheus in production, but have multiple concerns : 

1) in the following link -> https://neo4j.com/docs/morpheus-user-guide/preview/morpheus/overview/
   morpheus is describe as a neo4j-enterprise feature. (that builds on CAPS) . yet this repository changed from CAPS to morpheus , and has an apache license. does this mean that morpheus is entirely apache-2 licensed?

2) is there still ongoing development or a roadmap ?  is there a chance that using morpheus now (basing flows on top of its API's) would break once SPARK-3.0 comes out (with it's cypher features) ?

Thank you ! this is an amazing piece of SW which currently i believe tops GraphX \ GraphFrames and would really like to see it grow

**Comment by Mats-SX** [comment]
Hello @MarcianoAvihay and thanks for reaching out. I've also answered your email as well, but I will respond here on the questions you outline:

1. The documentation is a little bit outdated. CAPS (Cypher for Apache Spark) is not a thing anymore, but has been renamed to Morpheus. The idea was to have an open-core model, hosted under openCypher as openCypher Morpheus, and then an enterprise offering on top called Neo4j Morpheus, but as it stands today the open core is everything, and is hosted on this repository. Everything is Apache 2.0 licensed.

2. There is no ongoing development, and no roadmap. Morpheus is compatible with Spark 2.4, and will stay that way. Once Spark 3.0 comes out, Morpheus will most likely not be compatible. It will remain compatible with Spark 2.4.

Thank you for the kind words. We do think that property graphs are the way to go, but we would need support from within the established Spark community to move it forward. As a potential alternative, I recommend checking out our new Graph Data Science library: https://github.com/neo4j/graph-data-science, which is designed to solve massive-scale graph workloads in a scale-up architecture, close to the Neo4j database.
