### ISSUE TITLE
Read in spark and represent and save in neo4j 

### ISSUE THREAD

**Issue by MariaCardoso97** [opencypher/morpheus#949]
I read an HDFS file in spark. So far so good. But now I want to represent you on neo4j. How should I do? How do I create nodes and relationships? Does the spark have to be inside the neo4j container?

**Comment by jjaderberg** [comment]
Hi @MariaCardoso97, have you looked at the documentation of the Neo4j property graph data source? https://neo4j.com/docs/morpheus-user-guide/preview/caps/backends/neo4j/

There is also a "Neo4j workflow" example towards the end of the user guide that you can look at.

**Comment by jjaderberg** [comment]
Closing as expected to be resolved. Please reach out if you want to discuss further, but do be aware that development on this project is currently paused from our side and support is unfortunately no longer top of mind for the team.
