### ISSUE TITLE
Why the project is no longer maintained ?

### ISSUE THREAD

**Issue by suesunss** [opencypher/morpheus#950]
Hi,

I noticed that the README has been updated recently, saying that project is no longer actively maintained.

> This project is no longer actively maintained. If you want to know more, please reach out by creating an issue.

The project seems to be originally prepared to be integrated to Spark 3.0 as Spark Graph, as far as I am concerned from various tutorials of Neo4j and Databricks.

Could anyone point out the reason for stopping continuing developing this project which should be very interesting and promising ?

**Comment by Mats-SX** [comment]
@suesunss Thanks for reaching out to us following the update of the README. The project has in fact been effectively stale for about a year, but we didn't get around to communicate this until recently.

You are correct that the goal during 2019 was to work towards building the main parts of this project into a contribution to the Apache Spark mainline repository. We were fully prepared and were working towards that, but we were lacking support from the Apache Spark maintainers. We were initially sponsored by a PMC member, but as priorities shifted our efforts were blocked on lack of sponsor support. We tried to reach out to the Apache Spark maintainers but were ultimately unsuccessful in gathering the necessary interest and support, leading us to conclude that the interest in bringing property graphs with Cypher query support to Apache Spark is not well established within the Apache Spark community of maintainers. Conversely, Apache Spark users may disagree, however our efforts have now diverted elsewhere. (For reference, please consult the Apache Spark developer mailing lists.)

This being said, nothing has been set in stone with regards to this project's long-term plan. We still have a list of ideas on how to bring this forward, but in the short and mid term our communication is that we are not going to actively develop or maintain openCypher Morpheus. It will remain available in the current state for open source users (for forking or building and using) as well as the released binaries of the versions we have already published. We still hold firm the belief that the property graph data model could be useful and powerful in the Apache Spark ecosystem and I would recommend the best way I know of achieving a supported professional experience which is to use the Neo4j Spark Connector (https://github.com/neo4j-contrib/neo4j-spark-connector) together with the Neo4j graph database.

I hope this helps answering your questions and clarifying the situation.
All the best
Mats

**Comment by Triadelphia** [comment]
Very unfortunate that this project did not get picked up - I know there are a host of Spark users that would love connectivity with a property graph and use of Cypher... I hope it eventually gets the support that it deserves.

**Comment by s1ck** [comment]
> Very unfortunate that this project did not get picked up - I know there are a host of Spark users that would love connectivity with a property graph and use of Cypher... I hope it eventually gets the support that it deserves.

Thanks for the nice words. We put a lot of effort into this and would have loved to see it as a proper component of Spark. Unfortunately, the Spark PMCs thought different back then 🤷‍♀️
