### ISSUE TITLE
The future of Spark Graph and morpheus

### ISSUE THREAD

**Issue by lshilleto** [opencypher/morpheus#951]
Hey @s1ck, having just seen your latest commit https://github.com/opencypher/morpheus/commit/f54768bab48cab4ae1cf8e2030420fedd9ab18d3 I was wondering if I could get your perspective on the future of cypher on Spark and more generally Graphs on Spark. Is it fair to say the enhancements laid out in this talk https://databricks.com/session_eu19/graph-features-in-spark-3-0-integrating-graph-querying-and-algorithms-in-spark-graph-continues are no longer planned?

**Comment by s1ck** [comment]
Hey @lshilleto Thanks for your interest. @Mats-SX gave a full explanation on https://github.com/opencypher/morpheus/issues/950
Feel free to re-open if you have further questions.
