### ISSUE TITLE
Morpheus' Future

### ISSUE THREAD

**Issue by stevencox** [opencypher/morpheus#952]
Hi folks,

The README says 
```
NOTE

This project is no longer actively maintained. If you want to know more, please reach out by creating an issue.
```
I was building things to use Morpheus so I'd like to know more. Is there a future, a successor, or is this the end of the line for Morpheus?

**Comment by s1ck** [comment]
Hi Steven,

Thanks for your interest. @Mats-SX gave a detailed explanation on https://github.com/opencypher/morpheus/issues/950

Please let us know if you have further questions.
