### ISSUE TITLE
New releases coming soon ?

### ISSUE THREAD

**Issue by ChristinaCK7** [opencypher/morpheus#953]
Hi,
Is there any chance that this project will restart ?
Thx.

**Comment by Mats-SX** [comment]
Hello @ChristinaCK7 and thanks for reaching out to us. I would like to refer you to issue #950 where I've attempted to capture the current state of development for Morpheus.

If you have a specific business use case for which you would like to invest in Morpheus, please reach out to alicia.frame@neo4j.com.

Kind regards
Mats
