### ISSUE TITLE
Is it possible to add another function like id() but returns long instead of byte array

### ISSUE THREAD

**Issue by ministat** [opencypher/morpheus#956]
When I run the following cypher query, the results are byte arrays and unfriendly to read.
```
MATCH (n: name)-[:Linking {IsActive: true}]->(a: Account {Source: 10})
WHERE n.LinkingValue = 'FIVE|RISKTESTSUITE'
RETURN id(a)
```
The output are as follows.
```
╔══════════════════════════╗
║ id(n)                    ║
╠══════════════════════════╣
║ [-48, -63, -95, -115, 6] ║
║ [-48, -96, -47, -122, 3] ║
║ [-88, -95, 1]            ║
╚══════════════════════════╝
```
But I expect they are in the format as Gremlin outputs. How can I achieve that?
gremlin> g.V().hasLabel('name').has('LinkingValue','FIVE|RISKTESTSUITE').inE('Linking').has('IsActive',true).outV().hasLabel('Account').has('Source',10).id().toList()
==>1638424784
==>819220560
==>20648

**Comment by soerenreichardt** [comment]
Hello @ministat , thanks for opening the ticket. Unfortunately this project is no longer maintained and the knowledge of internals vanished a bit as well :) 
I digged a bit through the code though and found that we apparently encode ids using [a var long encoding](https://github.com/opencypher/morpheus/blob/master/morpheus-spark-cypher/src/main/scala/org/opencypher/morpheus/impl/expressions/EncodeLong.scala). That class also contains the code that reverses the operation. If you are using scala to execute your query you could use that function to map ids back to a long.

**Comment by ministat** [comment]
@soerenreichardt Thanks for your information. I composed a fix and it works for me:
