### ISSUE TITLE
Fail to run :okapi-ir:test

### ISSUE THREAD

**Issue by ministat** [opencypher/morpheus#957]
hi all, I want to run okapi-ir:test in my local env, but I encountered the following error. It looks like I missed ast-9.0-9.0.20190305-tests.jar, how can I get it?
```
/gradlew :okapi-ir:test
> Task :okapi-ir:compileTestScala FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':okapi-ir:compileTestScala'.
> Could not resolve all files for configuration ':okapi-ir:testCompileClasspath'.
   > Could not find ast-9.0-tests.jar (org.opencypher:ast-9.0:9.0.20190305).
     Searched in the following locations:
         file:/home/hongjizhang/.m2/repository/org/opencypher/ast-9.0/9.0.20190305/ast-9.0-9.0.20190305-tests.jar
   > Could not find util-9.0-tests.jar (org.opencypher:util-9.0:9.0.20190305).
     Searched in the following locations:
         file:/home/hongjizhang/.m2/repository/org/opencypher/util-9.0/9.0.20190305/util-9.0-9.0.20190305-tests.jar
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
```

**Comment by s1ck** [comment]
@ministat Unfortunately, the project is not actively maintained anymore. In case you want to go through figuring this out yourself, you can try to build opencypher artifacts from source: https://github.com/opencypher/front-end

**Comment by ministat** [comment]
@s1ck Thanks for your information. I successfully built the jars I needed from https://github.com/opencypher/front-end

**Comment by s1ck** [comment]
That's great. What are you doing with the project if I may ask?

**Comment by ministat** [comment]
Yes, I run Tinkerpop on Spark. In Gremlin's SparkGraphComputer, it runs the query in BSP (https://en.wikipedia.org/wiki/Bulk_synchronous_parallel) model together with Spark dataframe joins. That caused long iterations, and many Spark stages for some cases. I have not fully understand it, but my experiment indicates that the computation logic is inefficient.

SQL joins is fine in my perspective. Spark community has done many optimizations to improve the SQL join performance.

**Comment by s1ck** [comment]
Ok, yeah, I looked into that a few years back when I studied GraphX. I am not surprised that it's slow :)

Would be great if you could share some results of your evaluation once you're done. And sorry, that we can't maintain this project anymore, it's somewhat really cool :)

**Comment by ministat** [comment]
In current stage, I just selected some failed or long running gremlin queries for Morpheus evaluation. This has been done now, and I need to send the report for team discussion. In next step, if the team decides to adopt Morpheus, more queries will be evaluated.

Anyway, what I'm concerned is this project has been deactive. That deserves investment. For graph OLAP, Tinkerpop OLAP cannot be used in production, and there is no other open-source tool better than Morpheus in my eyes. Do you think is there any open-source tool similar like Morpheus ?

**Comment by ministat** [comment]
@s1ck Morpheus Cypher get 3X~20X compared with Gremlin OLAP in my test scenarios:
